[package]
name = "eventsource"
version = "0.3.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

description = "Library for accessing EventSource/Server-Sent Events endpoints"
repository = "https://github.com/lluchs/eventsource"
license = "MIT"
keywords = ["http"]

[features]
default = ["with-reqwest"]

# Enable the reqwest-based client.
with-reqwest = ["reqwest"]

[dependencies]
error-chain = "0.11.0"
reqwest = { version = "0.8.0", optional = true }
